steps:
    - name: 'gcr.io/cloud-builders/docker'
      args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/springboot_new:$SHORT_SHA', '.' ]
    - name: 'gcr.io/cloud-builders/docker'
      args: ['push', 'gcr.io/$PROJECT_ID/springboot_new:$SHORT_SHA']
    - name: "gcr.io/cloud-builders/gke-deploy"
      args:
      - run
      - --filename=kubernetes-config-file
      - --image=gcr.io/$PROJECT_ID/springboot_new:$SHORT_SHA
      - --location=us-central1-c
      - --cluster=app-cluster