steps:
    - name: 'gcr.io/cloud-builders/docker'
      args: [ 'build', '-t', 'gcr.io/jenkins-275110/springboot_new:latest', '.' ]
    - name: 'gcr.io/cloud-builders/docker'
      args: ['push', 'gcr.io/jenkins-275110/springboot_new:latest']
    - name: "gcr.io/cloud-builders/gke-deploy"
      args:
      - run
      - --filename=deployment.yaml
      - --image=gcr.io/jenkins-275110/springboot_new:latest
      - --location=us-central1-c
      - --cluster=app-cluster