apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-web-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot-web-api
  template:
    metadata:
      labels:
        app: springboot-web-api
    spec:
      containers:
      - image: gcr.io/jenkins-275110/springboot_new:latest
        name: springboot
        imagePullPolicy: Always

---

kind: Service
apiVersion: v1
metadata:
  name: springbootwebservice
spec:
  selector:
    app: springboot-web-api
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  type: LoadBalancer
